const sdkTypes = ['firebase', 'unity'] as const

interface Metadata {
  appVersion: string
  db: string
  sdk: SdkType
  time: { end: string; start: string }
}
type SdkType = (typeof sdkTypes)[number]

const autoCollect: Record<SdkType, { events: string[]; props: string[] }> = {
  firebase: {
    events: [
      'ad_click',
      'ad_exposure',
      'ad_impression',
      'ad_query',
      'ad_reward',
      'adunit_exposure',
      'app_clear_data',
      'app_exception',
      'app_remove',
      'app_store_refund',
      'app_store_subscription_cancel',
      'app_store_subscription_convert',
      'app_store_subscription_renew',
      'app_update',
      'click',
      'dynamic_link_app_open',
      'dynamic_link_app_update',
      'dynamic_link_first_open',
      'error',
      'fiam_action',
      'fiam_dismiss',
      'fiam_impression',
      'file_download',
      'firebase_campaign',
      'firebase_in_app_message_action',
      'firebase_in_app_message_dismiss',
      'firebase_in_app_message_impression',
      'first_open',
      'first_visit',
      'form_start',
      'form_submit',
      'in_app_purchase',
      'notification_dismiss',
      'notification_foreground',
      'notification_open',
      'notification_receive',
      'os_update',
      'page_view',
      'screen_view',
      'scroll',
      'session_start',
      'user_engagement',
      'video_complete',
      'video_progress',
      'video_start',
      'view_search_results'
    ],
    props: [
      'accept_time',
      'aclid',
      'ad_event_id',
      'ad_unit_code',
      'anid',
      'campaign',
      'campaign_info_source',
      'cancellation_reason',
      'click_timestamp',
      'client_id',
      'content',
      'cp1',
      'currency',
      'deferred_analytics_collection',
      'engagement_time_msec',
      'exposure_time',
      'fatal',
      'file_extension',
      'file_name link_classes',
      'firebase_error',
      'firebase_error_value',
      'firebase_previous_class',
      'firebase_previous_id',
      'firebase_previous_screen',
      'firebase_screen',
      'firebase_screen_class',
      'firebase_screen_id',
      'form_destination',
      'form_id',
      'form_name',
      'form_submit_text',
      'free_trial',
      'ga_session_id',
      'ga_session_number',
      'gclid',
      'ignore_referrer',
      'introductory_price',
      'label',
      'link_classes',
      'link_domain',
      'link_id',
      'link_text',
      'link_url',
      'medium',
      'message_channel',
      'message_device_time',
      'message_id',
      'message_name',
      'message_time',
      'message_type',
      'outbound',
      'page_location',
      'page_referrer',
      'page_title',
      'previous_app_version',
      'previous_first_open_count',
      'previous_gmp_app_id',
      'previous_os_version',
      'price',
      'product_id',
      'quantity',
      'renewal_count',
      'reset_analytics_cause',
      'reward_type',
      'reward_value',
      'search_term',
      'source',
      'subscription',
      'system_app',
      'system_app_update',
      'term',
      'timestamp',
      'topic',
      'traffic_type',
      'updated_with_analytics',
      'value',
      'video_current_time',
      'video_duration',
      'video_percent',
      'video_provider',
      'video_title',
      'video_url',
      'visible'
    ]
  },
  unity: {
    events: [],
    props: []
  }
}
export { autoCollect, sdkTypes }
export type { Metadata, SdkType }
