'use client'

import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from '@a/ui/form'
import { Input } from '@a/ui/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@a/ui/select'
import { Slider } from '@a/ui/slider'
import { useSuspenseQuery } from '@tanstack/react-query'
import { startCase } from 'es-toolkit/string'

import Textarea from '~/components/textarea'
import { api } from '~/trpc/react'

import useSoloForm from '../use-solo-form'

const Page = () => {
  const { data, form, saveIndicator } = useSoloForm(),
    { llm } = api(),
    { data: llms } = useSuspenseQuery(llm.all.queryOptions())
  return data?.language ? (
    <Form {...form}>
      {saveIndicator}
      <form className='space-y-8'>
        <FormField
          control={form.control}
          name='welcomeMessage'
          render={({ field }) => (
            <FormItem className='gap-1'>
              <FormLabel>{startCase(field.name)}</FormLabel>
              <FormDescription className='mb-2'>
                The first message the agent will say. If empty, the agent will wait until user start the conversation.
              </FormDescription>
              <FormControl>
                <Textarea className='min-h-24' maxLength={20_000} {...field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name='llm'
          render={({ field }) => (
            <FormItem className='flex items-center justify-between'>
              <div className='space-y-1'>
                <FormLabel className='uppercase'>{field.name}</FormLabel>
                <FormDescription>Select the language model for this agent</FormDescription>
              </div>
              <FormMessage />
              <Select onValueChange={field.onChange} value={field.value ?? undefined}>
                <FormControl>
                  <SelectTrigger className='data-placeholder:normal-case' disabled={field.disabled}>
                    <SelectValue placeholder='Select an LLM' />
                  </SelectTrigger>
                </FormControl>
                <SelectContent>
                  {llms
                    .filter(l => l.languages.includes(data.language))
                    .map(v => (
                      <SelectItem key={v.id} value={v.id}>
                        {v.model}
                      </SelectItem>
                    ))}
                </SelectContent>
              </Select>
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name='temperature'
          render={({ field }) => (
            <FormItem className='flex items-center justify-between'>
              <div className='space-y-1'>
                <FormLabel>{startCase(field.name)}</FormLabel>
                <FormDescription>
                  Parameter to control the creativity or randomness of the responses generated by LLM
                </FormDescription>
              </div>
              <FormMessage />
              <FormControl>
                <div className='w-28 space-y-1'>
                  <input
                    {...field}
                    className='w-32 text-center outline-none'
                    max={1}
                    min={0}
                    onChange={e => field.onChange(e.target.valueAsNumber)}
                    step={0.05}
                    type='number'
                  />
                  <Slider
                    disabled={field.disabled}
                    max={1}
                    min={0}
                    onValueChange={([v]) => field.onChange(v)}
                    step={0.05}
                    value={[field.value ?? 0]}
                  />
                </div>
              </FormControl>
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name='maxTokens'
          render={({ field }) => (
            <FormItem className='flex items-center justify-between'>
              <div className='space-y-1'>
                <FormLabel>{startCase(field.name)}</FormLabel>
                <FormDescription>
                  Maximum number of tokens LLM can predict. A limit will be applied if the value is greater than 0.
                </FormDescription>
              </div>
              <FormMessage />
              <FormControl>
                <Input {...field} className='w-28' onChange={e => field.onChange(e.target.valueAsNumber)} type='number' />
              </FormControl>
            </FormItem>
          )}
        />
      </form>
    </Form>
  ) : null
}

export default Page
